[build]
  command = "ng build --configuration production && npm run json-server"
  publish = "dist/trabajoparcial"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/Marriotelo"
  status = 200
